export const SEARCH_POKEMON = 'SEARCH_POKEMON';
export const ERROR_POKEMON = 'ERROR_POKEMON';

export const SET_POKEMON_GROUP = 'SET_POKEMON_GROUP';
export const SET_POKEMON_TOTAL_COUNT = 'SET_POKEMON_TOTAL_COUNT';
export const SET_POKEMON = 'SET_POKEMON';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export const TOGGLE_IS_LOADER = 'TOGGLE_IS_LOADER';
